### ISSUE TITLE
Delegation verification should check `allowedAction`

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/zcapld#20]
If `allowedAction` is specified by a parent capability, then a child capability may not be given any new actions beyond what was specified by the parent. Note that if the parent does not specify `allowedAction` then any actions may be specified in the child.

**Comment by llorllale** [comment]
@dlongley what use cases are there for `allowedAction` being empty?

Prohibiting empty `allowedAction` has the nice property of a verifier needing just the parent to ensure proper attenuation.

**Comment by dlongley** [comment]
`allowedAction` is a restriction on the actions that can be taken -- and if no restrictions are needed then this is omitted. Regardless, the entire chain must always be present when verifying an invocation. #73 also makes embedding the entire chain a requirement.
