### ISSUE TITLE
Remove bitcore alias after jsonld-signatures >= 5

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/zcapld#33]
it might be possible to remove the bitcore alias from this project in the future:

https://github.com/digitalbazaar/ocapld.js/blob/226a44f01d4ed99fc4db45b87dc1387b69e24a49/karma.conf.js#L96-L99

This is for karma tests, but we are phasing out our use bitcore in various libraries.

Steps:

1. upgrade jsonld-signatures to a version >= 5
2. try to remove all the bitcore aliases.

**Comment by dmitrizagidulin** [comment]
Implemented, closing.
