### ISSUE TITLE
Add flag/mechanism to skip capability compaction to security context

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/zcapld#7]
Capabilities that are known to define security context terms in the same way as defined in the security v2 context should not have to go through JSON-LD processing (compaction) to be used. A flag or mechanism should be provided to the API caller to enable skipping compaction for certain capabilities.

**Comment by mattcollier** [comment]
This refers to the compact operation here: https://github.com/digitalbazaar/ocapld.js/blob/master/lib/utils.js#L93

**Comment by dlongley** [comment]
Addressed by #73.
